# Generated by Django 4.0.6 on 2022-07-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='created_on')),
                ('note_title', models.CharField(max_length=50)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notebook')),
            ],
        ),
    ]
